---
abstract: 'Cache using sliding time-based expiration strategy'
author:
  - 'Alex Efros <powerman-asdf@ya.ru>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Sliding
no_index:
  directory:
    - inc
    - t
requires:
  EV: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.000000
